export type Payment = {
    /**
     * Unique ID of the payment generated by the server. Maximum length allowed [2000]
     */
    payment_id: string;

    /**
     * Mode through which payment is made. This can be check, cash, creditcard, banktransfer, bankremittance,
     * autotransaction or others. In german
     * Maximum length [100]
     * Get all methods by: https://inventory.zoho.eu/api/v1/meta/paymentmodes
     */
    payment_mode: "braintree" | "paypal" | "banktransfer" | "Banküberweisung";

    /**
     * Amount paid in the respective payment.
     */
    amount: number;

    /**
     * Denotes any additional bank charges. - Use this field for paypal etc. transaction costs.
     */
    bank_charges: number;

    /**
     * Date on which payment is made. Date Format [yyyy-mm-dd]
     */
    date: string;

    /**
     * Reference number generated for the payment.
     * A string of your choice can also be used as the reference number. Maximum length of the reference number [100]
     * Use for example the invoice number, that this payment corresponds to.
     */
    reference_number: string;

    /**
     * Description about the payment.
     */
    description: string;

    /**
     * Customer ID of the customer involved in the payment.
     */
    customer_id: string;

    created_time: string;
    last_modified_time: string;

    /**
     * ID of the cash/ bank account the payment has to be deposited.
     * Use this field to write the payment to a specific bank or online payments account.
     * For example paypal, braintree or others.
     */
    account_id: string;

    /**
     * List of invoices associated with the payment. Each invoice object contains invoice_id,
     * invoice_number, date, invoice_amount, amount_applied and balance_amount.
     */
    invoices: {
        invoice_id: string;
        amount_applied: string;
    }[];
};
