/**
 * List of contact persons details.
 */
export type ContactPerson = {
    /**
     * Unique ID generated by the server for the contact person
     */
    contact_person_id: string;

    contact_id: string;
    salutation: string;
    first_name: string;
    last_name: string;
    email: string;
    phone: string;
    mobile: string;
    is_primary_contact: boolean;
    skype: string;
    designation: string;
    department: string;
    is_added_in_portal: boolean;
    enable_portal: boolean;
    created_time: string;
    updated_time: string;
};

export type CreateContactPerson =
    /**
     * Required fields
     */
    Omit<
        Pick<ContactPerson, "last_name" | "contact_id"> &
            /**
             * Optional fields
             */
            Partial<
                Omit<
                    ContactPerson,
                    "contact_person_id" | "created_time" | "updated_time"
                >
            >,
        "is_added_in_portal"
    >;
