export type Organization = {
    organization_id: string;
    name: string;
    contact_name: string;
    email: string;
    is_default_org: false;
    plan_type: number;
    tax_group_enabled: true;
    zi_migration_status: 0;
    plan_name: string;
    plan_period: string;
    language_code: string;
    fiscal_year_start_month: 0;
    account_created_date: string;
    account_created_date_formatted: string;
    time_zone: string;
    is_org_active: true;
    currency_id: string;
    currency_code: string;
    currency_symbol: string;
    currency_format: string;
    price_precision: 2;
};
