/**
 * The ShipmentOrder can be included in a already shipped package
 * This types defines the values, that the Zoho API returns us
 */
export type ShipmentOrder = {
    shipment_id: string;
    shipment_number: string;
    shipment_date: string;
    shipment_date_with_time: string;
    tracking_number: string;
    delivery_date: string;
    delivery_date_with_time: string;
    shipment_type: string;
    associated_packages_count: number;
    carrier: string;
    service: string;
    delivery_days: string;
    delivery_guarantee: false;
    tracking_url: string;
    is_carrier_shipment: true;
};

/**
 * These are the packages created for Sales Orders
 */
export type Package = {
    /**
     * Unique ID generated by the server for the package. This is used as an identifier.
     */
    package_id: string;

    /**
     * Package number of the Sales Order.
     */
    package_number: string;

    /**
     * The current status of the Sales Order.
     */
    status: string;

    /**
     * Detailed status.
     */
    detailed_status: string;

    /**
     * Status message of package.
     */
    status_message: string;

    /**
     * Unique ID generated by the server for the shipment. This is used as an identifier.
     */
    shipment_id: string;

    /**
     * Shipment number of the package.
     */
    shipment_number: string;

    /**
     * Shipment status of the package.
     */
    shipment_status: string;

    /**
     * Name of the shipping carrier.
     */
    carrier: string;

    /**
     * In most cases the same as carrier
     */
    delivery_method: string;

    /**
     * Name of the service provided by the carrier.
     */
    service: string;

    /**
     * Tracking number of shipment.
     */
    tracking_number: string;

    is_tracking_enabled: boolean;

    /**
     * Date, that the package got created
     */
    date: string;

    /**
     * Shipment date of the Sales Order.
     * ISO 8601 format - YYYY-MM-DDThh:mm:ssTZD
     */
    shipment_date: string;

    shipment_order?: ShipmentOrder;

    /**
     * The expected days to be taken for the delivery.
     */
    delivery_days: string;

    /**
     * Delivery guarantee of the shipment can be true or false.
     */
    delivery_guarantee: boolean;
};
