/**
 * Create a Sales Order
 *
 * Creates a new Sales Order in Zoho Inventory. Description about extra
 * parameter ignore_auto_number_generation - Ignore auto sales order number
 * generation for this sales order. This mandates the Sales Order number to be
 * entered. Allowed Values true and false. oauthscope :
 * ZohoInventory.salesorders.CREATE
 */
export type CreateSalesOrder = {
  /**
   * Unique ID generated for the customer. This is used as an identifier.
   */
  customer_id: string;

  /**
   * The Sales Order number. This is unique for each sales order.
   */
  salesorder_number: string;

  /**
   * The date for the Sales Order.
   */
  date?: Date;

  /**
   * Shipment date of the Sales Order.
   */
  shipment_date?: Date;

  /**
   * Custom fields
   */
  custom_fields?: {
    /**
     * Id of the custom field
     */
    custom_field_id: string;

    /**
     * Index of the custom field
     */
    index: string;

    /**
     * Label of the custom field
     */
    label: string;

    /**
     * Value of the custom field
     */
    value: string;
  }[];

  /**
   * Reference number of the Sales Order
   */
  reference_number?: string;

  /**
   * A sales order can contain multiple line items.
   */
  line_items: {
    /**
     * Unique ID generated by the server for the item. This is used as an
     * identifier.
     */
    item_id?: string;

    /**
     * Name of the line item.
     */
    name?: string;

    /**
     * Description of the line item.
     */
    description?: string;

    /**
     * Rate / Selling Price of the line item.
     */
    rate?: number;

    /**
     * Quantity of the line item.
     */
    quantity?: number;

    /**
     * Unit of line item.
     */
    unit?: string;

    /**
     * Unique ID generated by the server for the tax. This is used as an
     * identifier.
     */
    tax_id?: number;

    /**
     * Name of the tax applied on the line item.
     */
    tax_name?: string;

    /**
     * Denotes the type of the tax. This can either be a single tax or a tax
     * group.
     */
    tax_type?: string;

    /**
     * Percentage of the tax.
     */
    tax_percentage?: number;

    /**
     * Total of line item.
     */
    item_total?: number;

    /**
     * Unique ID generated by the server for the ware houses
     */
    warehouse_id?: number;

    /**
     * Add HSN/SAC code for your goods/services
     * India Edition only
     */
    hsn_or_sac?: number;
  }[];

  /**
   * Notes for the Sales Order.
   */
  notes?: string;

  /**
   * Terms for the Sales Order.
   */
  terms?: string;

  /**
   *  The percentage of Discount applied.
   */
  discount?: string;

  /**
   * Used to check whether the discount is applied before tax or after tax.
   */
  is_discount_before_tax?: boolean;

  /**
   * Type of discount. Allowed values are entity_level,item_level. For
   * entity_level type, discount is applied at entity level and the node
   * discount resides outside the line_items node.For item_level type, discount
   * is applied at item level and the node discount resides inside each
   * line_item under the line_items node
   */
  discount_type?: string;

  /**
   * Shipping charges that can be applied to the Sales Order.
   */
  shipping_charge?: number;

  /**
   * Delivery method of the shipment.
   */
  delivery_method?: string;

  /**
   * Adjustment on the Sales Order's total.
   */
  adjustment?: number;

  /**
   * Unique ID generated by the server for the Pricebook. This is used as an
   * identifier.
   */
  pricebook_id?: number;

  /**
   * Unique ID generated by the server for the sales person. This is used as an
   * identifier.
   */
  salesperson_id?: number;

  /**
   * Description for the adjustment.
   */
  adjustment_description?: string;

  /**
   * Used to specify whether the line item rates are inclusive or exclusive of
   * tax.
   */
  is_inclusive_tax?: boolean;

  /**
   * Exchange rate of the currency, with respect to the base currency.
   */
  exchange_rate?: number;

  /**
   * Unique ID generated by the server for the Template. This is used as an
   * identifier.
   */
  template_id: number;

  /**
   * Sales order can have files attached to them. Each attachment has the
   * following attributes
   */
  documents?: {
    /**
     * Checks whether the sales order can be sent as a mail or not.
     */
    can_send_in_mail?: boolean;
    /**
     * This indicates the name of the file.
     */
    file_name?: string;
    /**
     * This indicates the type of the file.
     */
    file_type?: string;
    /**
     * This indicates the size of the formatted file.
     */
    file_size_formatted?: string;
    /**
     * This indicates the chronological number of the attachment.
     */
    attachment_order?: number;
    /**
     * Unique ID generated by the server for the document. This is used as an
     * identifier.
     */
    document_id?: number;

    /**
     * this indicates the size of the attached file.
     */
    file_size?: number;
  }[];

  /**
   * Unique Id generated by the server for address in contacts page. To add a
   * billing address to sales order, send the address_id using this node. Else,
   * the default billing address for that contact is used
   */
  billing_address_id?: string;

  /**
   * Unique Id generated by the server for address in contacts page. To add a
   * shipping address to sales order, send the address_id using this node. Else,
   * the default shipping address for that contact is used place_of_supply
   */
  shipping_address_id?: string;

  /**
   * Place where the goods/services are supplied to. (If not given, place of
   * contact given for the contact will be taken)
   *
   * India Edition only.
   */
  place_of_supply?: string;

  /**
   * Choose whether the contact is GST
   * registered/unregistered/consumer/overseas.
   *
   * India Edition only.
   */
  gst_treatment?: "business_gst" | "business_none" | "overseas" | "consumer";

  /**
   * 15 digit GST identification number of the customer.
   * India Edition only.
   */
  gst_no?: string;
};
