
/**
 * Invoices created for the Sales Order
 */
export type Invoice ={

    /**
     * Unique ID generated by the server for the invoice. This is used as an identifier.
     */
    invoice_id: number

    /**
     * The number of the Invoice.
     */
    invoice_number: string

    /**
     * The current status of the Sales Order.
     */
    status: string

    /**
     * The date for the Sales Order.
     * ISO 8601 format - YYYY-MM-DDThh:mm:ssTZD
     */
    date: string

    /**
     * Due date for the Invoice.
     * ISO 8601 format - YYYY-MM-DDThh:mm:ssTZD
     */
    due_date: string

    /**
     * Total amount of the Sales Order.
     */
    total: number

    /**
     * Balance due for the invoice.
     */
    balance: number
  }